ASSETS = [

    {"id": "okta", "name": "Okta SSO", "type": "identity",
     "criticality": 5, "business_unit": "IT", "record_count": 1200},
    {"id": "active_directory", "name": "Active Directory", "type": "identity",
     "criticality": 5, "business_unit": "IT", "record_count": 1200},
    {"id": "aws_iam", "name": "AWS IAM", "type": "identity",
     "criticality": 5, "business_unit": "Engineering", "record_count": 0},
    {"id": "vault", "name": "HashiCorp Vault", "type": "identity",
     "criticality": 5, "business_unit": "Security", "record_count": 0},
    {"id": "vpn", "name": "Corporate VPN", "type": "identity",
     "criticality": 3, "business_unit": "IT", "record_count": 0},
    {"id": "mfa_service", "name": "MFA Service", "type": "identity",
     "criticality": 4, "business_unit": "Security", "record_count": 1200},

    {"id": "github_org", "name": "GitHub Organisation", "type": "code",
     "criticality": 4, "business_unit": "Engineering", "record_count": 0},
    {"id": "repo_payments", "name": "payments-api Repository", "type": "code",
     "criticality": 5, "business_unit": "Engineering", "record_count": 0},
    {"id": "repo_frontend", "name": "web-frontend Repository", "type": "code",
     "criticality": 3, "business_unit": "Engineering", "record_count": 0},
    {"id": "repo_infra", "name": "infrastructure Repository", "type": "code",
     "criticality": 5, "business_unit": "Engineering", "record_count": 0},
    {"id": "ci_runner", "name": "GitHub Actions Runner", "type": "code",
     "criticality": 5, "business_unit": "Engineering", "record_count": 0},
    {"id": "artifact_registry", "name": "Container Registry", "type": "code",
     "criticality": 4, "business_unit": "Engineering", "record_count": 0},
    {"id": "sonarqube", "name": "SonarQube", "type": "code",
     "criticality": 2, "business_unit": "Engineering", "record_count": 0},

    {"id": "aws_prod_account", "name": "AWS Production Account", "type": "cloud",
     "criticality": 5, "business_unit": "Engineering", "record_count": 0},
    {"id": "aws_dev_account", "name": "AWS Development Account", "type": "cloud",
     "criticality": 3, "business_unit": "Engineering", "record_count": 0},
    {"id": "s3_customer_exports", "name": "S3 Customer Exports Bucket", "type": "cloud",
     "criticality": 5, "business_unit": "Sales", "record_count": 890000},
    {"id": "s3_backups", "name": "S3 Backup Bucket", "type": "cloud",
     "criticality": 5, "business_unit": "IT", "record_count": 2400000},
    {"id": "s3_logs", "name": "S3 Logs Bucket", "type": "cloud",
     "criticality": 2, "business_unit": "Security", "record_count": 0},
    {"id": "eks_cluster", "name": "EKS Kubernetes Cluster", "type": "cloud",
     "criticality": 5, "business_unit": "Engineering", "record_count": 0},
    {"id": "lambda_functions", "name": "Lambda Functions", "type": "cloud",
     "criticality": 4, "business_unit": "Engineering", "record_count": 0},
    {"id": "cloudflare", "name": "Cloudflare DNS", "type": "cloud",
     "criticality": 4, "business_unit": "IT", "record_count": 0},

    {"id": "customer_db", "name": "Customer Database", "type": "data",
     "criticality": 5, "business_unit": "Sales", "record_count": 2400000},
    {"id": "production_db", "name": "Production Database", "type": "data",
     "criticality": 5, "business_unit": "Engineering", "record_count": 1800000},
    {"id": "payments_db", "name": "Payments Database", "type": "data",
     "criticality": 5, "business_unit": "Finance", "record_count": 640000},
    {"id": "analytics_warehouse", "name": "Analytics Warehouse", "type": "data",
     "criticality": 4, "business_unit": "Sales", "record_count": 3100000},
    {"id": "staging_db", "name": "Staging Database", "type": "data",
     "criticality": 3, "business_unit": "Engineering", "record_count": 120000},
    {"id": "redis_cache", "name": "Redis Session Cache", "type": "data",
     "criticality": 4, "business_unit": "Engineering", "record_count": 45000},
    {"id": "elasticsearch", "name": "Elasticsearch Cluster", "type": "data",
     "criticality": 3, "business_unit": "Engineering", "record_count": 950000},

    {"id": "slack", "name": "Slack Workspace", "type": "collaboration",
     "criticality": 3, "business_unit": "All", "record_count": 0},
    {"id": "confluence", "name": "Confluence Wiki", "type": "collaboration",
     "criticality": 3, "business_unit": "All", "record_count": 0},
    {"id": "jira", "name": "Jira", "type": "collaboration",
     "criticality": 2, "business_unit": "Engineering", "record_count": 0},
    {"id": "google_drive", "name": "Google Drive", "type": "collaboration",
     "criticality": 4, "business_unit": "All", "record_count": 0},
    {"id": "email_gateway", "name": "Email Gateway", "type": "collaboration",
     "criticality": 4, "business_unit": "IT", "record_count": 1200},
    {"id": "zoom", "name": "Zoom", "type": "collaboration",
     "criticality": 2, "business_unit": "All", "record_count": 0},


    {"id": "payroll", "name": "Payroll System", "type": "business",
     "criticality": 5, "business_unit": "Finance", "record_count": 1200},
    {"id": "hr_portal", "name": "HR Portal", "type": "business",
     "criticality": 4, "business_unit": "HR", "record_count": 1200},
    {"id": "salesforce", "name": "Salesforce CRM", "type": "business",
     "criticality": 4, "business_unit": "Sales", "record_count": 540000},
    {"id": "netsuite", "name": "NetSuite ERP", "type": "business",
     "criticality": 5, "business_unit": "Finance", "record_count": 78000},
    {"id": "zendesk", "name": "Zendesk Support", "type": "business",
     "criticality": 3, "business_unit": "Support", "record_count": 310000},
    {"id": "docusign", "name": "DocuSign", "type": "business",
     "criticality": 4, "business_unit": "Legal", "record_count": 24000},
]